[package]
name = "routeradm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
propolis = { path = "/home/ry/src/propolis/propolis", features = ["falcon"] }
