[package]
name = "p4rs"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4"
slog = { version = "2.7", features = ["max_level_trace"] }
slog-term = "2.9"
slog-async = "2.7"
slog-envlogger = "2.2"
bitvec = "1.0"
colored = "2.0"
